stages:
- test
- build
- deploy
- upgrade

variables:
  GIT_SSL_NO_VERIFY: "true"
  RANCHER_URL: "http://10.141.11.53:8080"
  CONTAINER_IHUB_CODE_IMAGE: $CI_REGISTRY/integrations/ihub:$CI_BUILD_REF_NAME

before_script:
  - echo $CI_BUILD_REF

composer_and_unit_testing:
  stage: test
  image: gitlab.favorit:4567/integrations/docker:php-fpm
  services:
    - redis:3.2
  script:
    - sh ./run/dev/install-rancher.sh
    - ./vendor/bin/codecept run
  cache:
    key: $CI_BUILD_REF_NAME
    untracked: true
    paths:
      - ./vendor
  artifacts:
    when: on_failure
    name: $CI_BUILD_REF_NAME
    paths:
      - ./tests/_output
      - ./storage/logs
      - ./.env.testing
    expire_in: 1 day

build_php_7.0_dev:
  stage: build
  image: gitlab.favorit:4567/integrations/docker:php-fpm
  script:
    - bash ./run/dev/install-rancher.sh
  cache:
    key: $CI_BUILD_REF_NAME
    paths:
      - ./vendor
  artifacts:
    paths:
      - ./vendor
      - ./
    expire_in: 1 week
  only:
    - dev

build_php_7.0_master:
  stage: build
  image: gitlab.favorit:4567/integrations/docker:php-fpm
  script:
    - bash ./run/prod/decode.sh
    - bash ./run/prod/install-rancher.sh
  cache:
    key: $CI_BUILD_REF_NAME
    paths:
      - ./vendor
  artifacts:
    paths:
      - ./vendor
      - ./
    expire_in: 1 week
  only:
    - master

push_code:
  stage: deploy
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.favorit:4567
    - rm -rf .git .gitlab-ci.yml .gitignore .env.example
    - ls -liah
    - docker build -t $CONTAINER_IHUB_CODE_IMAGE .
    - docker push $CONTAINER_IHUB_CODE_IMAGE
  only:
    - dev
    - master

rancher_upgrade:
  stage: upgrade
  image: gitlab.favorit:4567/integrations/rancher-rest-wrapper:master
  script:
    - export RANCHER_URL=$RANCHER_URL && export RANCHER_ACCESS_KEY=$RANCHER_ACCESS_KEY && export RANCHER_SECRET_KEY=$RANCHER_SECRET_KEY
    - upgrade --environment dev-ihub --stack ihub --service php-fpm
    - upgrade --environment dev-ihub --stack ihub --service nginx
  only:
    - dev

manual_push_dev_code:
  stage: deploy
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.favorit:4567
    - rm -rf .git .gitlab-ci.yml .gitignore .env.example
    - ls -liah
    - docker build -t $CONTAINER_IHUB_CODE_IMAGE .
    - docker push $CONTAINER_IHUB_CODE_IMAGE
  when: manual

manual_dev_rancher_upgrade:
  stage: upgrade
  image: gitlab.favorit:4567/integrations/rancher-rest-wrapper:master
  script:
    - export RANCHER_URL=$RANCHER_URL && export RANCHER_ACCESS_KEY=$RANCHER_ACCESS_KEY && export RANCHER_SECRET_KEY=$RANCHER_SECRET_KEY
    - upgrade --environment dev-ihub --stack ihub --service php-fpm
    - upgrade --environment dev-ihub --stack ihub --service nginx
  only:
    - dev
  when: manual