stages:
- test
- compile_project
- build_docker_image
- deploy_to_servers
- manual_deploy_to_servers

variables:
  GIT_SSL_NO_VERIFY: "true"
  RANCHER_DEV_URL: "http://10.141.11.53:8080"
  RANCHER_PROD_URL: "http://10.120.12.41:8080"
  CONTAINER_IHUB_CODE_IMAGE: $CI_REGISTRY/integrations/ihub:$CI_BUILD_REF_NAME

#====================== templates ======================#
.template_dev: &template_dev
  tags:
    - de2gl03d_dind_1
  only:
    - dev

.template_prod: &template_prod
  tags:
    - de2gl03p_dind_1
  only:
    - master
    - tags

.template_compile_n_test: &template_compile_n_test
  <<: *template_dev
  stage: test
  image: gitlab.favorit:4567/integrations/docker:php-fpm-dev
  services:
    - redis:3.2
  cache:
    key: $CI_BUILD_REF_NAME
    untracked: true
    paths:
      - ./vendor
  artifacts:
    when: on_failure
    name: $CI_BUILD_REF_NAME
    paths:
      - ./tests/_output
      - ./storage/logs
      - ./.env.testing
    expire_in: 1 day

.template_build_docker_image: &template_build_docker_image
  stage: build_docker_image
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.favorit:4567
    - rm -rf .git .gitlab-ci.yml .gitignore .env.example ./run
    - docker build -t $CONTAINER_IHUB_CODE_IMAGE .
    - docker push $CONTAINER_IHUB_CODE_IMAGE

.template_build_docker_image: &template_build_docker_image_dev
  <<: *template_dev
  <<: *template_build_docker_image

.template_build_docker_image: &template_build_docker_image_prod
  <<: *template_prod
  <<: *template_build_docker_image


#====================== templates ======================#

fail_build_for_incorrect_branches:
  tags:
    - de2gl03d_dind_1
  stage: test
  script:
    - echo "Not corrected branch name. You should pass /^(?![a-zA-Z]{1,6}-[0-9]{1,3}-).*$/"
    - exit 1
  only:
    - /^(?![a-zA-Z]{1,6}-[0-9]{1,3}-).*$/
  except:
    - dev
    - master

test_features_n_dev:
  <<: *template_compile_n_test
  script:
    - bash ./run/dev/install-rancher.sh
    - ./vendor/bin/codecept run
  only:
    - /^[a-zA-Z]{1,6}-[0-9]{1,3}-.*$/
    - dev

test_on_dev_env_prod:
  <<: *template_compile_n_test
  script:
    - bash ./run/prod/tests.sh
  only:
    - master
    - tags

compile_dev:
  <<: *template_dev
  stage: compile_project
  image: gitlab.favorit:4567/integrations/docker:php-fpm-dev
  script:
    - rm -rf .env .env.testing .git
    - bash ./run/dev/install-rancher.sh
  cache:
    key: $CI_BUILD_REF_NAME
    paths:
      - ./vendor
  artifacts:
    paths:
      - ./vendor
      - ./
    expire_in: 1 day
  only:
    - dev

compile_prod:
  <<: *template_prod
  stage: compile_project
  image: gitlab.favorit:4567/integrations/docker:php-fpm-master
  script:
    - export http_proxy="http://10.120.12.56:3128"
    - export https_proxy="http://10.120.12.56:3128"
    - rm -rf .env .env.testing ./tests .git
    - bash ./run/prod/decode.sh
    - bash ./run/prod/install-rancher.sh
    - rm -rf ./run/prod/install-rancher.sh
  cache:
    key: $CI_BUILD_REF_NAME
    paths:
      - ./vendor
  artifacts:
    paths:
      - ./vendor
      - ./
    expire_in: 1 day
  only:
    - master
    - tags

build_docker_image_dev:
  <<: *template_build_docker_image_dev
  only:
    - dev

build_docker_image_prod:
  <<: *template_build_docker_image_prod
  only:
    - tags

deploy_to_servers_dev:
  <<: *template_dev
  stage: deploy_to_servers
  image: gitlab.favorit:4567/integrations/rancher-rest-wrapper:master
  script:
    - export RANCHER_URL=$RANCHER_DEV_URL && export RANCHER_ACCESS_KEY=$RANCHER_DEV_ACCESS_KEY && export RANCHER_SECRET_KEY=$RANCHER_DEV_SECRET_KEY
    - upgrade --environment dev-ihub --stack ihub --service php-fpm --new-sidekicks0-image $CONTAINER_IHUB_CODE_IMAGE
    - upgrade --environment dev-ihub --stack ihub --service nginx --new-sidekicks0-image $CONTAINER_IHUB_CODE_IMAGE
  only:
    - dev

manual_deploy_to_servers_prod:
  <<: *template_prod
  stage: deploy_to_servers
  image: gitlab.favorit:4567/integrations/rancher-rest-wrapper:master
  script:
    - export RANCHER_URL=$RANCHER_PROD_URL && export RANCHER_ACCESS_KEY=$RANCHER_PROD_ACCESS_KEY && export RANCHER_SECRET_KEY=$RANCHER_PROD_SECRET_KEY
    - upgrade --environment ihub --stack ihub --service php-fpm --new-sidekicks0-image $CONTAINER_IHUB_CODE_IMAGE
    - upgrade --environment ihub --stack ihub --service nginx --new-sidekicks0-image $CONTAINER_IHUB_CODE_IMAGE
    - upgrade --environment ihub --stack ihub --service php-fpm-system --new-sidekicks0-image $CONTAINER_IHUB_CODE_IMAGE
  only:
    - tags
  when: manual