stages:
- build
- deploy
- upgrade

variables:
  GIT_SSL_NO_VERIFY: "true"
  RANCHER_URL: "http://10.141.11.53:8080"
  RANCHER_ACCESS_KEY: "3FB11832B4F1A1D4138A"
  RANCHER_SECRET_KEY: "H3MNqJ6DSNmMbFUQxpsjyiy1ggE1zsDEZxpCL188"
  CONTAINER_IHUB_CODE_IMAGE: $CI_REGISTRY/integrations/ihub:$CI_BUILD_REF_NAME

before_script:
  - echo $CI_BUILD_REF
  

try_to_build_7.0:
  stage: build
  image: gitlab.favorit:4567/integrations/docker:php-fpm
  allow_failure: true
  script:
    - sh ./run/install-rancher.sh
    - ./vendor/bin/codecept run -d
  cache:
    key: $CI_BUILD_REF_NAME
    untracked: true
    paths:
      - ./vendor
  artifacts:
    when: always
    name: $CI_BUILD_REF_NAME
    paths:
      - ./tests/_output
      - ./storage/logs
    expire_in: 1 day

build_7.0:
  stage: build
  image: gitlab.favorit:4567/integrations/docker:php-fpm
  script:
    - sh ./run/install-rancher.sh
  cache:
    key: $CI_BUILD_REF_NAME
    paths:
      - ./vendor
  artifacts:
    paths:
      - ./vendor
      - ./
    expire_in: 1 week
  only:
    - dev
    - master

push_code:
  stage: deploy
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.favorit:4567
    - rm -rf .git .gitlab-ci.yml .gitignore .env.example
    - ls -liah
    - docker build -t $CONTAINER_IHUB_CODE_IMAGE .
    - docker push $CONTAINER_IHUB_CODE_IMAGE
  only:
    - dev
    - master

rancher_upgrade:
  stage: upgrade
  image: gitlab.favorit:4567/integrations/rancher-rest-wrapper:master
  script:
    - export RANCHER_URL=$RANCHER_URL && export RANCHER_ACCESS_KEY=$RANCHER_ACCESS_KEY && export RANCHER_SECRET_KEY=$RANCHER_SECRET_KEY
    - upgrade --environment dev-ihub --stack ihub --service php-fpm
    - upgrade --environment dev-ihub --stack ihub --service nginx
  only:
    - dev

manual_push_code:
  stage: deploy
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.favorit:4567
    - rm -rf .git .gitlab-ci.yml .gitignore .env.example
    - ls -liah
    - docker build -t $CONTAINER_IHUB_CODE_IMAGE .
    - docker push $CONTAINER_IHUB_CODE_IMAGE
  when: manual

manual_rancher_upgrade:
  stage: upgrade
  image: gitlab.favorit:4567/integrations/rancher-rest-wrapper:master
  script:
    - export RANCHER_URL=$RANCHER_URL && export RANCHER_ACCESS_KEY=$RANCHER_ACCESS_KEY && export RANCHER_SECRET_KEY=$RANCHER_SECRET_KEY
    - upgrade --environment dev-ihub --stack ihub --service php-fpm
    - upgrade --environment dev-ihub --stack ihub --service nginx
  only:
    - dev
  when: manual