<?xml version='1.0' encoding='UTF-8'?>
<definitions
        xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
        xmlns:wsp="http://www.w3.org/ns/ws-policy"
        xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
        xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:tns="http://ws.platform.commersite.com/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        targetNamespace="http://ws.platform.commersite.com/"
        name="PlatformControllerWSService">
    <types>
        <xsd:schema>
            <xsd:import
                    namespace="http://ws.platform.commersite.com/"
                    schemaLocation="https://pcws.casino.com:443/portal/PlatformControllerWS?xsd=1" />
        </xsd:schema>
        <xsd:schema>
            <xsd:import
                    namespace="http://ws.platform.betsite/"
                    schemaLocation="https://pcws.casino.com:443/portal/PlatformControllerWS?xsd=2" />
        </xsd:schema>
    </types>
    <message name="getUserData">
        <part name="parameters" element="tns:getUserData" />
    </message>
    <message name="getUserDataResponse">
        <part name="parameters" element="tns:getUserDataResponse" />
    </message>
    <message name="Exception">
        <part name="fault" element="tns:Exception" />
    </message>
    <message name="getAccountBalance">
        <part name="parameters" element="tns:getAccountBalance" />
    </message>
    <message name="getAccountBalanceResponse">
        <part name="parameters" element="tns:getAccountBalanceResponse" />
    </message>
    <message name="addDepositEntry">
        <part name="parameters" element="tns:addDepositEntry" />
    </message>
    <message name="addDepositEntryResponse">
        <part name="parameters" element="tns:addDepositEntryResponse" />
    </message>
    <message name="addWithdrawEntry">
        <part name="parameters" element="tns:addWithdrawEntry" />
    </message>
    <message name="addWithdrawEntryResponse">
        <part name="parameters" element="tns:addWithdrawEntryResponse" />
    </message>
    <message name="rollBackWithdraw">
        <part name="parameters" element="tns:rollBackWithdraw" />
    </message>
    <message name="rollBackWithdrawResponse">
        <part name="parameters" element="tns:rollBackWithdrawResponse" />
    </message>
    <message name="cancelTransaction">
        <part name="parameters" element="tns:cancelTransaction" />
    </message>
    <message name="cancelTransactionResponse">
        <part name="parameters" element="tns:cancelTransactionResponse" />
    </message>
    <message name="getPersistentSession">
        <part name="parameters" element="tns:getPersistentSession" />
    </message>
    <message name="getPersistentSessionResponse">
        <part name="parameters" element="tns:getPersistentSessionResponse" />
    </message>
    <message name="getAamsUserData">
        <part name="parameters" element="tns:getAamsUserData" />
    </message>
    <message name="getAamsUserDataResponse">
        <part name="parameters" element="tns:getAamsUserDataResponse" />
    </message>
    <portType name="PlatformControllerWS">
        <operation name="getUserData">
            <input
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/getUserDataRequest"
                    message="tns:getUserData" />
            <output
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/getUserDataResponse"
                    message="tns:getUserDataResponse" />
            <fault message="tns:Exception" name="Exception"
                   wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/getUserData/Fault/Exception"/>
        </operation>
        <operation name="getAccountBalance">
            <input
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/getAccountBalanceRequest"
                    message="tns:getAccountBalance" />
            <output
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/getAccountBalanceResponse"
                    message="tns:getAccountBalanceResponse" />
            <fault message="tns:Exception" name="Exception"
                   wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/getAccountBalance/Fault/Exception" />
        </operation>
        <operation name="addDepositEntry">
            <input
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/addDepositEntryRequest"
                    message="tns:addDepositEntry" />
            <output
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/addDepositEntryResponse"
                    message="tns:addDepositEntryResponse" />
            <fault message="tns:Exception" name="Exception"
                   wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/addDepositEntry/Fault/Exception"
            />
        </operation>
        <operation name="addWithdrawEntry">
            <input
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/addWithdrawEntryRequest"
                    message="tns:addWithdrawEntry" />
            <output
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/addWithdrawEntryResponse"
                    message="tns:addWithdrawEntryResponse" />
            <fault
                    message="tns:Exception" name="Exception"
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/addWithdrawEntry/Fault/Exception" />
        </operation>
        <operation name="rollBackWithdraw">
            <input
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/rollBackWithdrawRequest"
                    message="tns:rollBackWithdraw" />
            <output
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/rollBackWithdrawResponse"
                    message="tns:rollBackWithdrawResponse" />
            <fault
                    message="tns:Exception" name="Exception"
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/rollBackWithdraw/Fault/Exception" />
        </operation>
        <operation name="cancelTransaction">
            <input
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/cancelTransactionRequest"
                    message="tns:cancelTransaction" />
            <output
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/cancelTransactionResponse"
                    message="tns:cancelTransactionResponse" />
            <fault
                    message="tns:Exception" name="Exception"
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/cancelTransaction/Fault/Exception" />
        </operation>
        <operation name="getPersistentSession">
            <input
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/getPersistentSessionRequest"
                    message="tns:getPersistentSession" />
            <output
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/getPersistentSessionResponse"
                    message="tns:getPersistentSessionResponse" />
            <fault
                    message="tns:Exception" name="Exception"
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/getPersistentSession/Fault/Exception" />
        </operation>
        <operation name="getAamsUserData">
            <input
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/getAamsUserDataRequest"
                    message="tns:getAamsUserData" />
            <output
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/getAamsUserDataResponse"
                    message="tns:getAamsUserDataResponse" />
            <fault
                    message="tns:Exception" name="Exception"
                    wsam:Action="http://ws.platform.commersite.com/PlatformControllerWS/getAamsUserData/Fault/Exception"
            />
        </operation>
    </portType>
    <binding name="PlatformControllerWSPortBinding" type="tns:PlatformControllerWS">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
        <operation name="getUserData">
            <soap:operation soapAction="" />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="Exception">
                <soap:fault name="Exception" use="literal" />
            </fault>
        </operation>
        <operation name="getAccountBalance">
            <soap:operation soapAction="" />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="Exception">
                <soap:fault name="Exception" use="literal" />
            </fault>
        </operation>
        <operation name="addDepositEntry">
            <soap:operation soapAction="" />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="Exception">
                <soap:fault name="Exception" use="literal" />
            </fault>
        </operation>
        <operation name="addWithdrawEntry">
            <soap:operation soapAction="" />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="Exception">
                <soap:fault name="Exception" use="literal" />
            </fault>
        </operation>
        <operation name="rollBackWithdraw">
            <soap:operation soapAction="" />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="Exception">
                <soap:fault name="Exception" use="literal" />
            </fault>
        </operation>
        <operation name="cancelTransaction">
            <soap:operation soapAction="" />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="Exception">
                <soap:fault name="Exception" use="literal" />
            </fault>
        </operation>
        <operation name="getPersistentSession">
            <soap:operation soapAction="" />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
            <fault name="Exception">
                <soap:fault name="Exception" use="literal" />
            </fault>
        </operation>
    </binding>
    <service name="PlatformControllerWSService">
        <port name="PlatformControllerWSPort" binding="tns:PlatformControllerWSPortBinding">
            <soap:address location="https://pcws.casino.com:443/portal/PlatformControllerWS" />
        </port>
    </service>
</definitions>